### ISSUE TITLE
Add van Genechten to work

### ISSUE THREAD

**Issue by robinpoort** [timble/www.timble.net#14]
Doc: https://docs.google.com/a/timble.net/document/d/1k7oeOYMXR_kMMXBQj9mogBov5sYP8U4ePUpsscMkhc4/

**Comment by robinpoort** [comment]
@tomjanssens @stevenrombauts My first draft for the work item on the Timble page.

Tom: can you agree on an intro like this?
Steven: we need a bit of technical details as well

**Comment by stevenrombauts** [comment]
Added a couple of paragraphs about the application setup. Tried to keep it simple and short. Please review, @robinpoort :-)

**Comment by robinpoort** [comment]
@stevenrombauts reviewed and looking good.
@tomjanssens Added to #14 branch, could you check?
