### ISSUE TITLE
Better pagination for Jekyll

### ISSUE THREAD

**Issue by robinpoort** [timble/www.timble.net#17]
Write a blog about the new pagination used on Nooku, Timble, Joomaltools and OpenPolice

https://docs.google.com/document/d/1HVjzrDGAA2-iG6mMERLjBYMtFvf1WKsXqpojDf4yHgU/edit#

**Comment by robinpoort** [comment]
@tomjanssens Can you review this blog please?

**Comment by johanjanssens** [comment]
@robinpoort  Added some feedback.

**Comment by tomjanssens** [comment]
Added to Jekyll, ready to be reviewed @robinpoort.

**Comment by tomjanssens** [comment]
Published: http://www.timble.net/blog/2015/05/07/better-pagination-for-jekyll.html
