### ISSUE TITLE
Accessibility tools

### ISSUE THREAD

**Issue by tomjanssens** [timble/www.timble.net#4]
Short blog post about the different accessibility tools we use for testing color blindness, contrast, ...

**Comment by robinpoort** [comment]
https://docs.google.com/a/timble.net/document/d/1Smf6fDZdl4pEyqmTD2YQuG8Q1zSoWFK8Y2EoqWhgYCc/edit?usp=drive_web

@tomjanssens could you review this?

**Comment by robinpoort** [comment]
Blog is live
